server:
  port: 0
spring:
  application:
    name: airline-service
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/airflights
    username: postgres
    password: postgres
    schema: airline
  jpa:
    enabled: false
  flyway:
    enabled: true
    schemas: airline
    locations: classpath:db/migration
  cloud:
    circuitbreaker:
      enabled: true
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          organization-service:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
          employee-service:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
  cloud:
    discovery:
      reactive:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      orgClient:
        sliding-window-size: 20
        failure-rate-threshold: 50
        register-health-indicator: true
      employeeClient:
        sliding-window-size: 20
        failure-rate-threshold: 50
        register-health-indicator: true
  timelimiter:
    instances:
      orgClient:
        timeout-duration: 4s
      employeeClient:
        timeout-duration: 4s

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    healthcheck:
      enabled: true