server:
  port: 0
  forward-headers-strategy: framework
spring:
  application:
    name: airline-service
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/airflights
    username: postgres
    password: postgres
    properties:
      schema: airline
  flyway:
    enabled: true
    schemas: airline
    locations: classpath:db/migration
    user: postgres
    password: password
    url: jdbc:postgresql://postgres:5432/airflights

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    healthcheck:
      enabled: true