server:
  port: 0
  forward-headers-strategy: framework
spring:
  application:
    name: airport-service
  datasource:
    url: jdbc:postgresql://postgres:5432/airflights
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: airport
  flyway:
    enabled: true
    schemas: airport
    locations: classpath:db/migration
    cloud:
    openfeign:
      client:
        config:
          organization-service:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
          employee-service:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
resilience4j:
  circuitbreaker:
    instances:
      orgClient:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
      employeeClient:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
logging:
  level:
    com.airflights.airport: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.data.jpa: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE