server:
  port: 0
spring:
  application:
    name: airport-service
  datasource:
    url: jdbc:postgresql://postgres:5432/airflights
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: airport
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        connection.provider_disables_autocommit: true
        query.in_clause_parameter_padding: true
        batch_fetch_style: DYNAMIC
  flyway:
    enabled: true
    schemas: airport
    locations: classpath:db/migration
    baseline-on-migrate: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          organization-service:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
          employee-service:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
  task:
    execution:
      pool:
        core-size: 10
        max-size: 25
        queue-capacity: 100
      thread-name-prefix: blocking-task-

resilience4j:
  circuitbreaker:
    instances:
      orgClient:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-type: COUNT_BASED
      employeeClient:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-type: COUNT_BASED
  timelimiter:
    instances:
      orgClient:
        timeout-duration: 4s
      employeeClient:
        timeout-duration: 4s
  retry:
    instances:
      orgClient:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
      employeeClient:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.airflights.airport: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.data.jpa: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE