server:
  port: 0
spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://postgres:5432/airflights
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.default_schema: booking
  flyway:
    enabled: true
    schemas: booking
    locations: classpath:db/migration
  cloud:
    openfeign:
      client:
        config:
          flight-service:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
          passenger-service:
            connect-timeout: 2000
            read-timeout: 3000
            logger-level: basic
resilience4j:
  circuitbreaker:
    instances:
      flightClient:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.net.UnknownHostException
          - feign.RetryableException
      passengerClient:
        sliding-window-size: 20
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - java.net.UnknownHostException
          - feign.RetryableException
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
