spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - PreserveHostHeader
          routes:
            - id: flight-api
              uri: lb://flight-service
              predicates:
                - Path=/api/flights/**
            - id: booking-api
              uri: lb://booking-service
              predicates:
                - Path=/api/bookings/**
            - id: airline-api
              uri: lb://airline-service
              predicates:
                - Path=/api/airlines/**
            - id: airport-api
              uri: lb://airport-service
              predicates:
                - Path=/api/airports/**
            - id: passenger-api
              uri: lb://passenger-service
              predicates:
                - Path=/api/passengers/**
            - id: restricted-zone-api
              uri: lb://restrictedzone-service
              predicates:
                - Path=/api/restricted-zones/**

            - id: flight-docs
              uri: lb://flight-service
              predicates:
                - Path=/docs/flight/v3/api-docs
              filters:
                - RewritePath=/docs/flight/(?<segment>.*), /$\{segment}

            - id: booking-docs
              uri: lb://booking-service
              predicates:
                - Path=/docs/booking/v3/api-docs
              filters:
                - RewritePath=/docs/booking/(?<segment>.*), /$\{segment}
            - id: airline-docs
              uri: lb://airline-service
              predicates:
                - Path=/docs/airline/v3/api-docs
              filters:
                - RewritePath=/docs/airline/(?<segment>.*), /$\{segment}

            - id: airport-docs
              uri: lb://airport-service
              predicates:
                - Path=/docs/airport/v3/api-docs
              filters:
                - RewritePath=/docs/airport/(?<segment>.*), /$\{segment}

            - id: passenger-docs
              uri: lb://passenger-service
              predicates:
                - Path=/docs/passenger/v3/api-docs
              filters:
                - RewritePath=/docs/passenger/(?<segment>.*), /$\{segment}

            - id: restricted-zone-docs
              uri: lb://restrictedzone-service
              predicates:
                - Path=/docs/restricted-zone/v3/api-docs
              filters:
                - RewritePath=/docs/restricted-zone/(?<segment>.*), /$\{segment}
            
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          x-forwarded:
            enabled: true
            host-enabled: true
            port-enabled: true
            proto-enabled: true
            prefix-enabled: true
server:
  port: 8080
springdoc:
  swagger-ui:
    urls:
      - name: Flight
        url: /docs/flight/v3/api-docs
      - name: Booking
        url: /docs/booking/v3/api-docs
      - name: Airline
        url: /docs/airline/v3/api-docs
      - name: Airport
        url: /docs/airport/v3/api-docs
      - name: Passenger
        url: /docs/passenger/v3/api-docs
      - name: RestrictedZone
        url: /docs/restricted-zone/v3/api-docs
eureka:
  client:
    service-url:

      defaultZone: http://eureka-server:8761/eureka
